# 训练配置文件
training:
  # 基础参数
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  
  # 学习率调度
  scheduler:
    type: "cosine"  # cosine, step, plateau
    warmup_epochs: 5
    min_lr: 0.00001
  
  # 优化器设置
  optimizer:
    type: "adamw"  # adamw, sgd
    momentum: 0.9  # 仅SGD使用
    
  # 损失函数
  loss:
    type: "crossentropy"
    label_smoothing: 0.1
    
  # 数据增强
  augmentation:
    # 基础变换
    resize: 512
    crop_size: 512
    
    # 随机变换
    horizontal_flip: 0.5
    vertical_flip: 0.0
    rotation: 15
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    
    # 高级变换
    mixup_alpha: 0.2
    cutmix_alpha: 1.0
    
  # 验证设置
  validation:
    split_ratio: 0.2
    eval_frequency: 1  # 每几个epoch验证一次
    
  # 早停设置
  early_stopping:
    patience: 10
    min_delta: 0.001
    
  # 检查点保存
  checkpoint:
    save_frequency: 5  # 每几个epoch保存一次
    save_best_only: true
    monitor: "val_accuracy"  # val_loss, val_accuracy

# GPU设置
device:
  # 自动检测GPU
  auto_select: true
  
  # 手动指定设备
  device_id: 0
  
  # 混合精度训练
  mixed_precision: true
